/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ALaUneRouteImport } from './routes/a-la-une'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as CultureRouteImport } from './routes/culture'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as PolitiqueDeConfidentialiteRouteImport } from './routes/politique-de-confidentialite'
import { Route as ScienceRouteImport } from './routes/science'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as ArticleSlugRouteImport } from './routes/article.$slug'
import { Route as DisciplineDRouteImport } from './routes/discipline.$d'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ALaUneRoute = ALaUneRouteImport.update({
  id: '/a-la-une',
  path: '/a-la-une',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const CultureRoute = CultureRouteImport.update({
  id: '/culture',
  path: '/culture',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const PolitiqueDeConfidentialiteRoute =
  PolitiqueDeConfidentialiteRouteImport.update({
    id: '/politique-de-confidentialite',
    path: '/politique-de-confidentialite',
    getParentRoute: () => rootRouteImport,
  } as any)
const ScienceRoute = ScienceRouteImport.update({
  id: '/science',
  path: '/science',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticleSlugRoute = ArticleSlugRouteImport.update({
  id: '/article/$slug',
  path: '/article/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DisciplineDRoute = DisciplineDRouteImport.update({
  id: '/discipline/$d',
  path: '/discipline/$d',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-la-une': typeof ALaUneRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/culture': typeof CultureRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/politique-de-confidentialite': typeof PolitiqueDeConfidentialiteRoute
  '/science': typeof ScienceRoute
  '/videos': typeof VideosRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/discipline/$d': typeof DisciplineDRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-la-une': typeof ALaUneRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/culture': typeof CultureRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/politique-de-confidentialite': typeof PolitiqueDeConfidentialiteRoute
  '/science': typeof ScienceRoute
  '/videos': typeof VideosRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/discipline/$d': typeof DisciplineDRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-la-une': typeof ALaUneRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/culture': typeof CultureRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/politique-de-confidentialite': typeof PolitiqueDeConfidentialiteRoute
  '/science': typeof ScienceRoute
  '/videos': typeof VideosRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/discipline/$d': typeof DisciplineDRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-la-une'
    | '/contact'
    | '/cookies'
    | '/culture'
    | '/mentions-legales'
    | '/politique-de-confidentialite'
    | '/science'
    | '/videos'
    | '/article/$slug'
    | '/discipline/$d'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-la-une'
    | '/contact'
    | '/cookies'
    | '/culture'
    | '/mentions-legales'
    | '/politique-de-confidentialite'
    | '/science'
    | '/videos'
    | '/article/$slug'
    | '/discipline/$d'
  id:
    | '__root__'
    | '/'
    | '/a-la-une'
    | '/contact'
    | '/cookies'
    | '/culture'
    | '/mentions-legales'
    | '/politique-de-confidentialite'
    | '/science'
    | '/videos'
    | '/article/$slug'
    | '/discipline/$d'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ALaUneRoute: typeof ALaUneRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  CultureRoute: typeof CultureRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  PolitiqueDeConfidentialiteRoute: typeof PolitiqueDeConfidentialiteRoute
  ScienceRoute: typeof ScienceRoute
  VideosRoute: typeof VideosRoute
  ArticleSlugRoute: typeof ArticleSlugRoute
  DisciplineDRoute: typeof DisciplineDRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-la-une': {
      id: '/a-la-une'
      path: '/a-la-une'
      fullPath: '/a-la-une'
      preLoaderRoute: typeof ALaUneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/culture': {
      id: '/culture'
      path: '/culture'
      fullPath: '/culture'
      preLoaderRoute: typeof CultureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politique-de-confidentialite': {
      id: '/politique-de-confidentialite'
      path: '/politique-de-confidentialite'
      fullPath: '/politique-de-confidentialite'
      preLoaderRoute: typeof PolitiqueDeConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/science': {
      id: '/science'
      path: '/science'
      fullPath: '/science'
      preLoaderRoute: typeof ScienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/article/$slug': {
      id: '/article/$slug'
      path: '/article/$slug'
      fullPath: '/article/$slug'
      preLoaderRoute: typeof ArticleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discipline/$d': {
      id: '/discipline/$d'
      path: '/discipline/$d'
      fullPath: '/discipline/$d'
      preLoaderRoute: typeof DisciplineDRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ALaUneRoute: ALaUneRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  CultureRoute: CultureRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  PolitiqueDeConfidentialiteRoute: PolitiqueDeConfidentialiteRoute,
  ScienceRoute: ScienceRoute,
  VideosRoute: VideosRoute,
  ArticleSlugRoute: ArticleSlugRoute,
  DisciplineDRoute: DisciplineDRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
